### ISSUE TITLE
I's not work well in win10

### ISSUE THREAD

**Issue by Thinker888** [xdsswar/nfx-lib#1]
It seems to run well on win11, but still has some issues on win10, like still having the missing top border. 
for example, the title bar background color of the MainWindowWithFXML doesn't work, but the title bar background color of MenuWindow does work.
![00](https://github.com/xdsswar/nfx-lib/assets/89960293/9d6d56de-cfa8-43e4-b447-12183ab7cd21)
![11](https://github.com/xdsswar/nfx-lib/assets/89960293/9c86cfbf-58a2-4b31-877c-19b331034c54)
![22](https://github.com/xdsswar/nfx-lib/assets/89960293/c517fa82-76e9-4342-9b19-3a7ce2777fec)

**Comment by xdsswar** [comment]
Thanks a lot, I will work on these issues, I need to install w10
