### ISSUE TITLE
There are some issues with the jniHitTest() function in the AbstractNfxUndecoratedWindow class

### ISSUE THREAD

**Issue by HuaXiYan** [xdsswar/nfx-lib#5]
First of all, thank you for developing this library, it has been very helpful to me!

But I encountered some issues, this library interferes with the listener of the title bar button, **manifested as when the mouse enters the button, Within the initialize function located in the UndecoratedExample class the button will simultaneously trigger mouse entry(setOnMouseEntered) and exit(setOnMouseExited) events**

After my research, I am not sure if this is a bug in the JNI native method, but I have found that there are some issues with the **jniHitTest()** function in the **AbstractNfxUndecoratedWindow** class that I believe exist

1、The values of the parameters **x** and **y** of this function may **rebound** in certain situations. Specifically, when the mouse moves **vertically/horizontally**, the **x** and **y** values should show a **stable increase/decrease**, but sometimes they may jump **back to their previous values**

2、The first line of code for this function, **invalideSpots()**, is not necessary **because the for loop below will perform the same operation**

3、This function is for **invalideSpots()** in the loop; The code can be separated from the **if** statement and written outside the **for** loop to **ensure that this code is not executed repeatedly**

4、The **jniInvalidateSpots()** function may encounter competition issues with the **jniHitTest()** function, mainly manifested as **the setHovered of the HitSpot control repeatedly changing between true/false** when the mouse **leaves** the target area

The above is for reference only. Thank you again for developing this library!

**Comment by HuaXiYan** [comment]
Sorry, there were some issues with the previously submitted problem report, and I may have made a mistake... I have closed it.

**Comment by xdsswar** [comment]
no problem , Im planning to use Panama to remove the C/C++/JNI code and make all in java. I think it will be more customizable.

**Comment by HuaXiYan** [comment]
Thank you for developing this library! Its UI and features are very good, except for slightly high CPU and memory usage, but this is the best library I have found so far!!!

Looking forward to your new library in the future!😃😃😃

**Comment by xdsswar** [comment]
Thanks, I really did that for fun, but Im going to get serious about it in few months, right know I have a lot of work, but when I finish I will rewrite all in pure java, no more native code
